language: ruby
rvm:
  - 1.9.3
  - 2.1.4
script:
  - RAILS_ENV=test bundle exec rake db:migrate --trace
  - bundle exec rake db:test:prepare
  - bundle exec
before_script:
  - cp config/database.yml.travis config/database.yml
  - psql -c 'create database flashcards_db_test;' -U postgres