SORCERY_GITHUB_KEY: "ef9918be95c9859b7338"
SORCERY_GITHUB_SECRET: "4a6981b3903cb4e56d0eac08d7fecb8ca3352af"
SORCERY_GITHUB_CALLBACK_URL: http://0.0.0.0:3000/oauth/callback?provider=github

SORCERY_TWITTER_KEY: "r7UHz1P365SYgxX140UvTWh4X"
SORCERY_TWITTER_SECRET: "DrLV5kOY3NdwWsH9eKzGhOUMqvi1SQanjfqJPeYPdJJ0Wd70Ve"
SORCERY_TWITTER_CALLBACK_URL: http://0.0.0.0:3000/oauth/callback?provider=twitter