# Be sure to restart your server when you modify this file.

# Your secret key is used for verifying the integrity of signed cookies.
# If you change this key, all old signed cookies will become invalid!

# Make sure the secret is at least 30 characters and all random,
# no regular words or you'll be exposed to dictionary attacks.
# You can use `rake secret` to generate a secure secret key.

# Make sure the secrets in this file are kept private
# if you're sharing your code publicly.

development:
  secret_key_base: cee1d1dbb1a993ed5d6c6a75622b6e40a2a867fc4ca901ceb09f9e8161758d7b5086804b07e0ededff8ed4d64b9ecfdf224d3fa81a04aa4be5caf2d1c6a1419f

  sorcery_twitter_key: <%= ENV["SORCERY_TWITTER_KEY"] %>
  sorcery_twitter_secret: <%= ENV["SORCERY_TWITTER_SECRET"] %>
  sorcery_twitter_callback_url: <%= ENV["SORCERY_TWITTER_CALLBACK_URL"] %>

  sorcery_github_key: <%= ENV["SORCERY_GITHUB_KEY"] %>
  sorcery_github_secret: <%= ENV["SORCERY_GITHUB_SECRET"] %>
  sorcery_github_callback_url: <%= ENV["SORCERY_GITHUB_CALLBACK_URL"] %>

test:
  secret_key_base: e0a82cc1891b6403515c6bf59a5d60ca36fbf3135457538c3f4d3261c826fd753b1efaaf96d1ea8d3c56860118e75930353b0179a772a4f9cc07e44ce24c66c1

  sorcery_twitter_key: <%= ENV["SORCERY_TWITTER_KEY"] %>
  sorcery_twitter_secret: <%= ENV["SORCERY_TWITTER_SECRET"] %>

  sorcery_github_key: <%= ENV["SORCERY_GITHUB_KEY"] %>
  sorcery_github_secret: <%= ENV["SORCERY_GITHUB_SECRET"] %>

# Do not keep production secrets in the repository,
# instead read values from the environment.
production:
  secret_key_base: <%= ENV["SECRET_KEY_BASE"] %>

  sorcery_twitter_key: <%= ENV["SORCERY_TWITTER_KEY"] %>
  sorcery_twitter_secret: <%= ENV["SORCERY_TWITTER_SECRET"] %>
  sorcery_twitter_callback_url: <%= ENV["SORCERY_TWITTER_CALLBACK_URL"] %>

  sorcery_github_key: <%= ENV["SORCERY_GITHUB_KEY"] %>
  sorcery_github_secret: <%= ENV["SORCERY_GITHUB_SECRET"] %>
  sorcery_github_callback_url: <%= ENV["SORCERY_GITHUB_CALLBACK_URL"] %>
